add non-conservative convection term
Ceyron/exponax pull request #46
Opened 2024-10-21 09:20 UTC by qiauil

* add non-conservative convection term
* allow to swift between conservative convection and non-conservative convection in steppers

2024-10-21 10:09 UTC, Ceyron requested changes
Hi Qiang,

thanks for the updated PR. I left some remarks in the code.

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
>          with `∇ ⋅` the divergence operator and the outer product `u ⊗ u`.
This part of the docstring is now in the wrong place. Could you fix this?

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +            𝒩(u) = -b₁ u (u)ₓ
I thought we wanted to have the conservative form as 1/2 (u^2)_x in 1d?

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +            𝒩(u) = -b₁ ∇ ⋅ (u ⊗ u)
By the conclusion we made in the issues thread, there should be a 1/2 here

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +            𝒩(u) = -b₁ 1/2 u (1⃗ ⋅ ∇)u
non-conservative single-channel should not have the 1/2, right? (cf table in https://github.com/Ceyron/exponax/issues/43#issuecomment-2421861564)

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +        #conv_u=sum(
Can you remove the commented piece of code

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +            𝒩(u) = -b₁ 1/2 u (1⃗ ⋅ ∇)u
non-conservative single-channel mode should be without the 1/2

2024-10-21 10:09 UTC, Ceyron commented on exponax/nonlin_fun/_convection.py
> +            𝒩(u) = -b₁ 1/2 u (1⃗ ⋅ ∇)u
(also reflects what happens in the code below)

2024-10-21 10:09 UTC, Ceyron commented on exponax/stepper/_korteweg_de_vries.py
> +    conservaitve: bool
typo

2024-10-21 10:12 UTC, Ceyron commented
A couple more general remarks:

Can you run the pre-commit hook, being in the same folder as the repo and then:
```bash
pip install pre-commit
pre-commit install --install-hooks
pre-commit run --all-files
```

This should resolve code-linting checks.

And please keep docstrings to 80 characters in length if possible

2024-10-21 12:37 UTC, Ceyron commented
Thanks for the updates, some last stylistic requests:

1. In the `_convection.py` file: please add a newline under the `**Arguments:**` header, otherwise mkdocs will not correctly produce the documentation
2. Please use [rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) to ensure that the docstrings are at max 80 characters.

2024-10-21 13:07 UTC, qiauil commented
Hi, Felix,

The new commit has been pushed; please take a look.

2024-10-22 08:26 UTC, Ceyron commented
Thanks for all the work.

I just went over the code for a last time, and I think that the nonconservative eval functions (both for multi-channel and single-channel) should use the `u_hat_dealiased` for creating `nabla_u` in lines 167 and 228 of `_convection.py`. What do you think?

2024-10-22 09:05 UTC, qiauil commented
Hi, Felix,

Good point!
To be honest, I am not sure about that. Do you think the linear operation will change the frequency of the field?
Theoretically,  I would prefer to dealias the `nabla_u` as it is the actual one that does the nonlinear operation.

Anyway, I will currently modify the `nabla_u` term with the dealiased value; we could do some experiments later to see the difference.

2024-10-22 09:29 UTC, Ceyron commented
The linear operator (i.e., the `derivative_operator`) does not move energy between the modes.

Aliasing occurs when we element-wise multiply two states in state space. To avoid creating any (undesirable) aliases, according to Orszag's 2/3 rule, both factors in the product must be zero-ed out in the upper 1/3 frequency range (which is what `self. dealias` does). Hence, we need to have both `nabla_u` and `u` being dealiased. At least, that's my current understanding of dealiasing. We can talk about it more in a separate thread.

With the modifications, I will now merge the PR. Thanks for the work :). If you are up for it, it would also be cool to extend some of the unit tests for the new four permutations of convection, but I'd say that's a separate PR.

2024-10-22 09:29 UTC, merged